# Site settings
title: Intiworks Jekyll Template
email: inti.rodr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Programmer, designer, freelancer. Template site for my future small CMS projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: intiworks

# Build settings
markdown: kramdown
